### ISSUE TITLE
[Progress Checklist] TODO

### ISSUE THREAD

**Issue by Aerijo** [yitzchak/tree-sitter-latex#7]
A list of things the TextMate grammar supports that should be checked off to minimise shock to end users. I've added things that should / can be done on the Atom side too so we don't forget about them.

### In `latex.cson`
- [X] `\include` / `\input`
  - Leave scoping of file paths to a linter
- [X] sections
  - Support for starred versions In PR
- [x] `\ExplSyntaxOn`
  - https://tex.stackexchange.com/questions/108696/what-do-explsyntaxon-and-explsyntaxoff-do
  - Also `\ProvidesExplPackage`
- [X] `minted`, `lstlisting`, etc.
  - Covered here as verbatim; actual injections up to Atom
- [x] `luacode`
- [X] `alltt`
  - PR in progress
- [x] urls / hyperref
- [X] `aligned`, `gathered`, etc.
  - These don't cause math, so probably safe to leave them out of math specific rules
  - No point marking them invalid either, as the user might actually be in mathmode (good for linter to handle)
- [x] Arguments to `alignat` environment (and [similar](https://en.wikibooks.org/wiki/LaTeX/Advanced_Mathematics#Other_environments))
  - It's supposed to be of the form `\begin{alignat}{3}` where the number specifies columns. Possibly not needed here, but would like confirmation (Note: `language-latex` does require the argument)
- [x] `array`, `table`, `tabular[xy]`, etc.
- [x] `itemize`, `description`, `enumerate`
  - [x] and `\item`
- [x] `tikzpicture`
- [x] `comment` (the [environment](https://ctan.org/pkg/comment?lang=en))
- [x] `\(re)?new|provide)command`
- [x] `\Declare(?!OptionX?\\b)([A-Z][a-zA-Z]*)\\b`
  - [See here](https://github.com/area/language-latex/blob/05c94f63545cc0443a20cf8dfc7cc62b7edd784e/grammars/latex.cson#L1687-L1694). Not quite sure what this is for, though could just be handled on the Atom side?
- [x] `\bf`, `\it`, etc.
  - I don't think we need to mark them as deprecated in this parser
- [x] `\marginpar`
  - Not sure what to do with this
- [x] References and citations
- [x] Glossaries
- [x] Various constants such as `\textsterling`
  - Leave these to Atom

### In `tex.cson`
- [x] `\backmatter`, etc.
  - Leave to Atom - this can be handled with `match`
- [X] `\def`, etc
- [x] `\catcode`
  - There is some support currently, but I believe the argument form can vary and we should account for that
- [x] TeXShop style tag comments (`%:`)
- [x] Newline command symbol (and others like `\$`, `\%`)
  - Leave to Atom
- [x] A bunch of math commands

**Comment by yitzchak** [comment]
@Aerijo Just FYI, I am going to go after `\ExplSyntaxOn` next.

**Comment by yitzchak** [comment]
@Aerijo I've checked off `\bf`, `\it`, `\backmatter` and any zero parameter control sequences off this list. They can all be captured in Atom with `match`.

**Comment by yitzchak** [comment]
There are two different comment environments. In the base is a verbatim comment environment that always excludes the text and there is the comment package which defines a non-verbatim environment named `comment` plus the ability to define new environments. Supporting the latter would be difficult and I am not sure what the advantage would be since these environments are just regular text environments. 

Therefore, I'll add support for the base's verbatim environment.

**Comment by yitzchak** [comment]
@Aerijo Do you know of any LaTeX specific syntax packages? Specifically I am wondering about support for `tabular`, `itemize`, etc.  I'm not sure about adding a whole bunch of specific parsing code for these environments when I suspect that `text_env` probably covers them or at a minimum a simple variation of `text_env` with some arguments on the begin.

**Comment by Aerijo** [comment]
@yitzchak You mean Tree-sitter? Either way, no. I never even got round to it in my own grammar. I don't know the syntax well enough, and haven't seen what users do with it (as we don't want anything to be too rigid).

On a different note, I think I've got the JSON communication working between Atom and my language server, so that's nice. C++ is a pain, but hopefully it will pay off. I am planning to use this parser there once it's ready (it doesn't actually do anything yet).

**Comment by yitzchak** [comment]
@Aerijo Sorry, I meant the Atom syntax packages. `language-latex` seems to make tabular very complex and so I was wondering if anyone is actually using that in syntax package for highlighting. Currently this parser alignment tabs and newlines are not excluded from appearing in regular text, so attempting to parse cells seems kind of silly.

In other words, have tabular parse as:

```
(tabular_env
  (begin (cs) (group) (brack_group) (group))
  (text_mode)
  (end (cs) (group)))
```

As a side node, I just got `shortvrb` to work based on your `\verb` code.

**Comment by yitzchak** [comment]
@Aerijo Also, cool on your language server!

**Comment by yitzchak** [comment]
@Aerijo I think this is just about ready for a v0.1.0 release. I am going to add a few more LaTeX classs commands (`CheckCommand`, `IfFileExists`, etc) then it should have minimal functionality.

The following are things that I am probably going to push off to v0.2.0 that are supported by the legacy grammar.
* `\Sexpr` - this is usually a pseudo LaTeX command for Sweave/knitr.
* beamer and memoir class support. beamer overlays are just too much for an initial release.

@thomasjo FYI

**Comment by yitzchak** [comment]
@Aerijo published v.0.1.0 as [@dicy/tree-sitter-latex](https://www.npmjs.com/package/@dicy/tree-sitter-latex)
